#include <stdio.h>
#include <stdlib.h>
#include <time.h>
int main() {
    srand(time(0));
    int z = (rand() % 100 )+1 ;// z is number generated by the program;
    int  x = 0  , no_of_guesses;// Guessed by user is x;
    for(no_of_guesses = 1 ;x!=z ; no_of_guesses++){

    printf("Guess a number in between 1 to 100 \n");
    scanf("%d",&x);

            if(x<z){
        printf("Guess a higher number please :) \n");

    }
    else if ( x>z){
        printf("Guess a Lower number please :) \n");
        
    }
    
    else {
        printf(" Congrats You guessed the correct number :))) \n");
     break ;
    } 
    }
    printf("You guessed the number in %d guesses",no_of_guesses); 
    return 0;
}
